title: 痔疮
description: 科普与痔疮相关知识，健康你我。
theme: jekyll-theme-leap-day
show_downloads: false
google_analytics: UA-79883090-8
github: 
  is_project_page: true
  owner_url: https://blog.devhitao.com # 底部项目拥有者链接
  owner_name: hitao # 项目拥有者名字
  show_github_repo_url: false

# Custom 
show_theme_author: false  # Hosted on GitHub Pages &mdash; Theme by wumaokeji.net
show_email: true
admin_email: 2939083436@qq.com
show_website_license: true
company_url: https://www.zhichuang.online
company_name: 痔疮在线